%-------------------------------------------------------------------------------
%  TITLE PAGE
%-------------------------------------------------------------------------------

% goes here


%-------------------------------------------------------------------------------
%  COPYRIGHT PAGE
%-------------------------------------------------------------------------------
\newpage
~\vfill
\thispagestyle{empty}

\noindent\textbf{\Large Licence and Copyright}\\
\noindent Copyright \copyright 2015 Sylvia Osterrieder\\ % Copyright notice
% \noindent \textsc{Published by \Sexpr{mpa_mmu_msp}}\\ % Publisher
%\noindent \textsc{book-website.com}\\ % URL

%-------------------------------------------------------------------------------
%	TABLE OF CONTENTS
%-------------------------------------------------------------------------------
\pagestyle{empty} % No headers
\tableofcontents % Print the table of contents itself
%\cleardoublepage % Forces the first chapter to start on an odd page so it's on the right
\pagestyle{fancy} % Print headers again
